[package]
name = "custom_app"
version = "0.1.0"
authors = ["advaithm <advaith.madhukar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = "0.6.3"

